name: Integration Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - name: Update action.yml to build locally
      #   run: |
      #     sed -i 's/.*image\:.*/  image\: \"Dockerfile\"/' action.yml
      #     cat action.yml
      - name: Self test
        id: selftest
        uses: ./
        with:
          include: "test/"
          find: "world"
          replace: "there"
      - name: Check outputs and modified files
        run: |
          test "${{ steps.selftest.outputs.modifiedFiles }}" == "1"
          grep "Hello there" test/hello.txt
